
- fixity: "infixl 4 $>"
- fixity: "infixl 4 <$"
- fixity: "infixl 4 *>"
- fixity: "infixl 4 <*"

- group: {name: teaching,                   enabled: true}
- group: {name: dollar,                     enabled: true}
- group: {name: generalise,                 enabled: true}
- group: {name: generalise-for-conciseness, enabled: true}
- group: {name: lens,                       enabled: true}

- warn: {lhs: void, rhs: "(() <$)", name: Say what you mean}

- warn: {lhs: pure x <* y, rhs: x <$ y, name: Generalize}

# Generalize to Functor.
- error: {lhs: map,         rhs: fmap,    name: Generalize}
- error: {lhs: liftM,       rhs: fmap,    name: Generalize}
- error: {lhs: x `liftM` y, rhs: x <$> y, name: Generalize}

- error: {lhs: return, rhs: pure,   name: Generalize}
- error: {lhs: ap,     rhs: (<*>),  name: Generalize}
- error: {lhs: liftM2, rhs: liftA2, name: Generalize}
- error: {lhs: x >> y, rhs: x *> y, name: Generalize}
- error: {lhs: x << y, rhs: x <* y, name: Generalize}

# Generalize to Foldable.
- error: {lhs: concatMap, rhs: foldMap,   name: Generalize to Foldable}
- error: {lhs: concat,    rhs: fold,      name: Generalize to Foldable}
- error: {lhs: mconcat,   rhs: fold,      name: Generalize to Foldable}
- error: {lhs: mapM_,     rhs: traverse_, name: Generalize to Foldable}
- error: {lhs: forM_,     rhs: for_,      name: Generalize to Foldable}
- warn: {lhs: maybe mempty,          rhs: foldMap, name: Generalize to Foldable}
- warn: {lhs: either (const mempty), rhs: foldMap, name: Generalize to Foldable}
- warn: {lhs: fromMaybe mempty, rhs: fold}
- warn: {lhs: fromRight mempty, rhs: fold}

- error: {lhs: mapM, rhs: traverse, name: Generalize}
- error: {lhs: forM, rhs: for,      name: Generalize}

# Generalize to Semigroup.
- error: {lhs: x ++ y,  rhs: x <> y, name: Generalize}
- error: {lhs: mappend, rhs: (<>),   name: Generalize}

# Lens
- error: {lhs: Lens.view l (Lens.set l v s),   rhs: v}
- error: {lhs: set l (view l s) s,   rhs: s}
- error: {lhs: set l v' (set l v s), rhs: set l v' s}
- error: {lhs: "l <%@~ const f", rhs: "l <%~ f"}
- error: {lhs: preview l (review l b), rhs: Just b}
- error: {lhs: "mx ^? _Just", rhs: mx}
- error: {lhs: "x ^. to f", rhs: f x}
- error: {lhs: sets (over l), rhs: l}
- error: {lhs: over (sets l), rhs: l}
- error: {lhs: "x & (Lens.mapped .~ y)", rhs: "x $> y"}
- error: {lhs: "ask . Lens.view",      rhs: Lens.view, name: view already asks}
- error: {lhs: "ask (^. o)",      rhs: "(^. o)", name: view already asks}
- error: {lhs: "asks . Lens.view",     rhs: Lens.view, name: view already asks}
- error: {lhs: "ask . views",     rhs: views,   name: views already asks}
- error: {lhs: "ask . views o",   rhs: views o, name: views already asks}
- error: {lhs: "asks . views o",  rhs: views o, name: views already asks}

- warn: {lhs: over l f . over l g, rhs: over l (f . g)}
- warn: {lhs: to f . to g, rhs: to (f . g)}
- warn: {lhs: either Just (const Nothing), rhs: preview _Left}
- warn: {lhs: either (const Nothing) Just, rhs: preview _Right}

- ignore: {name: "Parse error"} # hlint can't keep up with GHC.
- ignore: {name: Use tuple-section} # low signal-to-noise
- ignore: {name: Use camelCase}
- ignore: {name: Use list literal}
- ignore: {name: Use void}
- ignore: {name: "Use ?~"}
