resolver: lts-17.4

flags:
  xmonad:
    generatemanpage: true

packages:
- ./

extra-deps:
- X11-1.9.2
- pandoc-2.11.3.2
- citeproc-0.3.0.3
- commonmark-0.1.1.2
- commonmark-extensions-0.2.0.4
- commonmark-pandoc-0.2.0.1

nix:
  packages:
    - zlib
    - xorg.libX11
    - xorg.libXrandr
    - xorg.libXScrnSaver
    - xorg.libXext
