resolver: lts-14.19

packages:
  - ./

extra-deps:
  - X11-1.8

nix:
 packages:
   - autoconf
   - gcc
   - pkgconfig
   - xorg.libX11
   - xorg.libXext
   - xorg.libXft
   - xorg.libXinerama
   - xorg.libXpm
   - xorg.libXrandr
   - xorg.libXrender
